name: React App Deployment # name of the workflow

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v4.0.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./build

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.4
